version: '3.8'
services:
  backend:
    build: .
    container_name: backend-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/housefit
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}